### ISSUE TITLE
Worker down

### ISSUE THREAD

**Issue by mastervash** [GewoonJaap/portainer-templates-CF-worker#2]
Template list started throwing an error in Portainer about a week ago. 

When opening [https://portainer-templates.mrproper.dev/template.json](https://portainer-templates.mrproper.dev/template.json) one is greated with 

```
Error 1101 Ray ID: 7da262afc7862b7c • 2023-06-20 07:44:15 UTC
Worker threw exception
```
____
Also just wanted to thank you, your aggregated list has come in clutch countless times. I share it with anyone just starting with Docker. 

For consideration; there is also an [additional list](https://raw.githubusercontent.com/ntv-one/portainer/main/template.json) that your worker doesn't query, it may have been created afterward.

**Comment by GewoonJaap** [comment]
Thanks for the heads-up! I am going to look at it right away and add your additional list :) Thanks!

**Comment by GewoonJaap** [comment]
It's up and running again :) Thanks again for the heads-up

**Comment by mastervash** [comment]
Incredible, thank you for addressing it so quickly. Fantastic work!

**Comment by mastervash** [comment]
Incredible, thank you for addressing it so quickly. Fantastic work!
